### ISSUE TITLE
Unable to understand how to use beangulp to import transactions

### ISSUE THREAD

**Issue by mbkamble** [beancount/beangulp#90]
With the overarching goal of moving my workflow from beancount v2 to v3, I have managed to build the beacount master branch using bazel. Fom what I have followed so far, beangulp is the replacemet for beancount.ingest . But I am lost in figuring out how to use beangulp. There is no top level app such as beangulp.py. The older candidate, ie bean-extract (and associated tool bean-identify, bean-file) appear to have been obsoleted.
The beangulp document on google-doc did not help to figure out how to run beangulp.
I would appreciate if anyone cpuld provide a short para worth of details on how this is to be setup. I am not intending to appear as a harsh crtitic and understand that this is bleeding edge, documentation may not be up to date, and developers have other primary jobs etc. I am just looking for a decent description to jump start transitioning my v2-era importers to v3, and at the moment am feeliing lost

**Comment by ThomasdenH** [comment]
There is a folder which has the structure of a beancount project: https://github.com/beancount/beangulp/tree/master/examples

That should give you some idea of how to use this!

**Comment by dnicolodi** [comment]
Building Beancount v3 with Bazel in the current state of things is not very useful unless your goal is to hack in the Beancount C++ code. The rewritten parser and all the code it depends on is build but it is not in any way hoked into the user facing interfaces. These still use the old C code that is build with setuptools.

Transitioning to Beancount v3 currently is maybe premature if you don't plan to hack on Beancount or other components. The few user facing changes in v3 are moving code to other projects (beangulp, beanprice, beanquery, ...) and removal of code that is considered obsolete.

If you want to use `beangulp` instead of `beancount.ingest` you can find an example in the `examples` directory in the repository, as @ThomasdenH already suggested. Some more documentation will eventually be published.
